name: Build and Deploy Java App to Azure Web App

on:
  push:
    branches:
      - main  # Or master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'  # Or 11 depending on your setup

      - name: Build with Maven
        run: mvn clean install

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: PHARMA_WEBAPP
          publish-profile: ${{ secrets.PHARMA_WEBAPP_PUBLISH_PROFILE }}
          package: target/*.jar
